name: Update Date and Time

on:
  schedule:
    - cron: '0 */2 * * *' # Runs every 2 hours

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get current date and time
        id: date
        run: |
          echo "CURRENT_DATE=$(date '+%d-%m-%Y %I:%M %p')" >> $GITHUB_ENV

      - name: Update last_updated.txt
        run: |
          echo "${{ env.CURRENT_DATE }}" > last_updated.txt

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add last_updated.txt
          git commit -m "Auto-update: ${{ env.CURRENT_DATE }}"
          git push
